### ISSUE TITLE
Problem with running app

### ISSUE THREAD

**Issue by antonxandre** [pvsvamsi/SystemAlertWindow#68]
hello i am not able to open the app with system_alert_window 0.5.0+1 it gets stuck in build build/app/outputs/flutter-apk/app-debug.apk. configure as per the documentation but I think it is out of date, could you help me please?

manifests
```
AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="br.com.admsistema.opensenses">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <queries>
    <intent>
        <action android:name="android.intent.action.TTS_SERVICE" />
    </intent>
</queries>

   <application
        android:name=".Application"
        android:label="opensenses"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
           
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
       
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Application.kt**
import `in`.jvapps.system_alert_window.SystemAlertWindowPlugin
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        SystemAlertWindowPlugin.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry) {
    SystemAlertWindowPlugin.registerWith(registry.registrarFor("in.jvapps.system_alert_window"));
    }
}

**pubspec.yaml**
```
name: opensenses
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.1.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  subtitle: ^0.1.0-beta.2
  flutter_tts: ^0.1.1
  subtitle_wrapper_package: ^2.0.1
  dio: ^4.0.0
  system_alert_window: ^0.5.0+1

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
```

**still stucking on build/app/outputs/flutter-apk/app-debug.apk**
